-- Supabase SQL Editor에서 실행하여 필요한 모든 테이블과 RLS(행 보안 정책)을 설정하세요.
-- 테이블명 앞에 anti_ 접두사가 붙습니다.

-- 1. anti_users 테이블
create table if not exists public.anti_users (
  id bigint generated by default as identity primary key,
  username text not null unique,
  password_hash text not null,
  role text not null default 'user',
  permissions text not null default '{}',
  created_at timestamptz not null default now()
);

-- 2. anti_sessions 테이블
create table if not exists public.anti_sessions (
  token text primary key,
  user_id bigint not null references public.anti_users(id) on delete cascade,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null
);

-- 3. anti_balances 테이블
create table if not exists public.anti_balances (
  user_id bigint primary key references public.anti_users(id) on delete cascade,
  usdt numeric(38, 8) not null default 0
);

-- 4. anti_positions 테이블
create table if not exists public.anti_positions (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.anti_users(id) on delete cascade,
  symbol text not null,
  side text not null,
  qty numeric(38, 12) not null default 0,
  entry_price numeric(38, 8) not null default 0,
  leverage int not null default 1,
  margin numeric(38, 8) not null default 0,
  created_at timestamptz not null default now()
);

-- 5. anti_trades 테이블
create table if not exists public.anti_trades (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.anti_users(id) on delete cascade,
  symbol text not null,
  side text not null,
  qty numeric(38, 12) not null default 0,
  entry_price numeric(38, 8) not null default 0,
  exit_price numeric(38, 8) not null default 0,
  leverage int not null default 1,
  pnl numeric(38, 8) not null default 0,
  created_at timestamptz not null default now()
);

-- 6. anti_profit_cards 테이블
create table if not exists public.anti_profit_cards (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.anti_users(id) on delete cascade,
  trade_id bigint not null,
  title text not null,
  note text not null default '',
  created_at timestamptz not null default now()
);

-- 7. anti_executions 테이블
create table if not exists public.anti_executions (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.anti_users(id) on delete cascade,
  symbol text not null,
  side text not null,
  price numeric(38, 8) not null default 0,
  qty numeric(38, 12) not null default 0,
  fee numeric(38, 8) not null default 0,
  pnl numeric(38, 8) not null default 0,
  created_at timestamptz not null default now()
);

-- 8. RLS 활성화 및 익명(anon) 접근에 대한 정책 생성 (모의 데모용)
alter table public.anti_users enable row level security;
alter table public.anti_sessions enable row level security;
alter table public.anti_balances enable row level security;
alter table public.anti_positions enable row level security;
alter table public.anti_trades enable row level security;
alter table public.anti_profit_cards enable row level security;
alter table public.anti_executions enable row level security;

drop policy if exists "allow_all_anti_users" on public.anti_users;
create policy "allow_all_anti_users" on public.anti_users for all to anon using (true) with check (true);

drop policy if exists "allow_all_anti_sessions" on public.anti_sessions;
create policy "allow_all_anti_sessions" on public.anti_sessions for all to anon using (true) with check (true);

drop policy if exists "allow_all_anti_balances" on public.anti_balances;
create policy "allow_all_anti_balances" on public.anti_balances for all to anon using (true) with check (true);

drop policy if exists "allow_all_anti_positions" on public.anti_positions;
create policy "allow_all_anti_positions" on public.anti_positions for all to anon using (true) with check (true);

drop policy if exists "allow_all_anti_trades" on public.anti_trades;
create policy "allow_all_anti_trades" on public.anti_trades for all to anon using (true) with check (true);

drop policy if exists "allow_all_anti_profit_cards" on public.anti_profit_cards;
create policy "allow_all_anti_profit_cards" on public.anti_profit_cards for all to anon using (true) with check (true);

drop policy if exists "allow_all_anti_executions" on public.anti_executions;
create policy "allow_all_anti_executions" on public.anti_executions for all to anon using (true) with check (true);
