-- 현재 Nuxt 앱(SQLite 기반)에서 Supabase로 "복제 저장"하기 위한 추가 테이블입니다.
-- (auth.users UUID 구조를 쓰지 않고, 앱의 local_user_id(INT)를 그대로 저장)
-- Supabase SQL Editor에서 실행하세요.

create table if not exists public.app_users (
  id bigint generated by default as identity primary key,
  local_user_id bigint not null,
  username text not null,
  role text not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_app_users_local_user_id on public.app_users(local_user_id);
create index if not exists idx_app_users_username on public.app_users(username);

create table if not exists public.app_login_events (
  id bigint generated by default as identity primary key,
  local_user_id bigint null,
  username text null,
  area text not null, -- main/admin
  success boolean not null default true,
  ip text null,
  user_agent text null,
  created_at timestamptz not null default now()
);

create index if not exists idx_app_login_events_created_at on public.app_login_events(created_at desc);
create index if not exists idx_app_login_events_user on public.app_login_events(local_user_id, created_at desc);

create table if not exists public.app_buys (
  id bigint generated by default as identity primary key,
  local_user_id bigint not null,
  symbol text not null,
  side text not null, -- long/short
  buy_time timestamptz not null default now(),
  buy_price numeric(38, 8) not null,
  qty numeric(38, 12) not null,
  margin numeric(38, 8) not null,
  leverage int not null,
  total_usdt numeric(38, 8) not null
);

create index if not exists idx_app_buys_user_time on public.app_buys(local_user_id, buy_time desc);

create table if not exists public.app_admin_credits (
  id bigint generated by default as identity primary key,
  admin_local_user_id bigint not null,
  target_local_user_id bigint not null,
  amount numeric(38, 8) not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_app_admin_credits_created_at on public.app_admin_credits(created_at desc);

-- RLS: 데모 목적상 anon insert 허용 (필요시 강화하세요)
alter table public.app_users enable row level security;
alter table public.app_login_events enable row level security;
alter table public.app_buys enable row level security;
alter table public.app_admin_credits enable row level security;

drop policy if exists "anon_insert_app_users" on public.app_users;
create policy "anon_insert_app_users"
on public.app_users for insert
to anon
with check (true);

drop policy if exists "anon_insert_app_login_events" on public.app_login_events;
create policy "anon_insert_app_login_events"
on public.app_login_events for insert
to anon
with check (true);

drop policy if exists "anon_insert_app_buys" on public.app_buys;
create policy "anon_insert_app_buys"
on public.app_buys for insert
to anon
with check (true);

drop policy if exists "anon_insert_app_admin_credits" on public.app_admin_credits;
create policy "anon_insert_app_admin_credits"
on public.app_admin_credits for insert
to anon
with check (true);

