-- Supabase SQL Editor에서 실행하여 필요한 모든 테이블과 RLS(행 보안 정책)을 설정하세요.

-- 1. users 테이블
create table if not exists public.users (
  id bigint generated by default as identity primary key,
  username text not null unique,
  password_hash text not null,
  role text not null default 'user',
  permissions text not null default '{}',
  created_at timestamptz not null default now()
);

-- 2. sessions 테이블
create table if not exists public.sessions (
  token text primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null
);

-- 3. balances 테이블
create table if not exists public.balances (
  user_id bigint primary key references public.users(id) on delete cascade,
  usdt numeric(38, 8) not null default 0
);

-- 4. positions 테이블
create table if not exists public.positions (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  symbol text not null,
  side text not null,
  qty numeric(38, 12) not null default 0,
  entry_price numeric(38, 8) not null default 0,
  leverage int not null default 1,
  margin numeric(38, 8) not null default 0,
  created_at timestamptz not null default now()
);

-- 5. trades 테이블
create table if not exists public.trades (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  symbol text not null,
  side text not null,
  qty numeric(38, 12) not null default 0,
  entry_price numeric(38, 8) not null default 0,
  exit_price numeric(38, 8) not null default 0,
  leverage int not null default 1,
  pnl numeric(38, 8) not null default 0,
  created_at timestamptz not null default now()
);

-- 6. profit_cards 테이블
create table if not exists public.profit_cards (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  trade_id bigint not null,
  title text not null,
  note text not null default '',
  created_at timestamptz not null default now()
);

-- 7. executions 테이블
create table if not exists public.executions (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  symbol text not null,
  side text not null,
  price numeric(38, 8) not null default 0,
  qty numeric(38, 12) not null default 0,
  fee numeric(38, 8) not null default 0,
  pnl numeric(38, 8) not null default 0,
  created_at timestamptz not null default now()
);

-- 8. RLS 활성화 및 익명(anon) 접근에 대한 정책 생성 (모의 데모용)
alter table public.users enable row level security;
alter table public.sessions enable row level security;
alter table public.balances enable row level security;
alter table public.positions enable row level security;
alter table public.trades enable row level security;
alter table public.profit_cards enable row level security;
alter table public.executions enable row level security;

drop policy if exists "allow_all_users" on public.users;
create policy "allow_all_users" on public.users for all to anon using (true) with check (true);

drop policy if exists "allow_all_sessions" on public.sessions;
create policy "allow_all_sessions" on public.sessions for all to anon using (true) with check (true);

drop policy if exists "allow_all_balances" on public.balances;
create policy "allow_all_balances" on public.balances for all to anon using (true) with check (true);

drop policy if exists "allow_all_positions" on public.positions;
create policy "allow_all_positions" on public.positions for all to anon using (true) with check (true);

drop policy if exists "allow_all_trades" on public.trades;
create policy "allow_all_trades" on public.trades for all to anon using (true) with check (true);

drop policy if exists "allow_all_profit_cards" on public.profit_cards;
create policy "allow_all_profit_cards" on public.profit_cards for all to anon using (true) with check (true);

drop policy if exists "allow_all_executions" on public.executions;
create policy "allow_all_executions" on public.executions for all to anon using (true) with check (true);
